import '../models/food_model.dart';

final List<Food> dummyFoods = [
  Food(name: "Ayam Goreng", calories: 245, protein: 22, carbs: 0, fat: 15),
  Food(name: "Nasi Putih", calories: 130, protein: 2, carbs: 28, fat: 0),
  Food(name: "Telur Rebus", calories: 78, protein: 6, carbs: 0, fat: 5),
  Food(name: "Salmon Panggang", calories: 206, protein: 22, carbs: 0, fat: 12),
  Food(name: "Roti Tawar", calories: 70, protein: 2, carbs: 13, fat: 1),
  Food(name: "Kentang Rebus", calories: 77, protein: 2, carbs: 17, fat: 0),
  Food(name: "Sayur Bayam", calories: 23, protein: 3, carbs: 4, fat: 0),
  Food(name: "Apel", calories: 52, protein: 0, carbs: 14, fat: 0),
  Food(name: "Pisang", calories: 89, protein: 1, carbs: 23, fat: 0),
  Food(name: "Susu Sapi", calories: 60, protein: 3, carbs: 5, fat: 3),
  Food(name: "Keju Cheddar", calories: 113, protein: 7, carbs: 1, fat: 9),
  Food(name: "Oatmeal", calories: 68, protein: 3, carbs: 12, fat: 1),
  Food(name: "Yogurt", calories: 59, protein: 10, carbs: 3, fat: 0),
  Food(name: "Ayam Panggang", calories: 190, protein: 25, carbs: 0, fat: 8),
  Food(name: "Tahu", calories: 76, protein: 8, carbs: 2, fat: 4),
  Food(name: "Tempe", calories: 193, protein: 20, carbs: 9, fat: 11),
  Food(name: "Ikan Tuna", calories: 132, protein: 28, carbs: 0, fat: 1),
  Food(name: "Kacang Almond", calories: 164, protein: 6, carbs: 6, fat: 14),
  Food(name: "Kacang Merah", calories: 127, protein: 9, carbs: 23, fat: 0),
  Food(name: "Brokoli", calories: 34, protein: 3, carbs: 7, fat: 0),
  Food(name: "Wortel", calories: 41, protein: 1, carbs: 10, fat: 0),
  Food(name: "Jagung Rebus", calories: 96, protein: 3, carbs: 21, fat: 1),
  Food(name: "Daging Sapi", calories: 250, protein: 26, carbs: 0, fat: 15),
  Food(name: "Udang Rebus", calories: 99, protein: 24, carbs: 0, fat: 1),
  Food(name: "Cokelat Hitam", calories: 546, protein: 4, carbs: 61, fat: 31),
  Food(name: "Air Putih", calories: 0, protein: 0, carbs: 0, fat: 0),
  Food(name: "Kopi Hitam", calories: 2, protein: 0, carbs: 0, fat: 0),
  Food(name: "Teh Hijau", calories: 0, protein: 0, carbs: 0, fat: 0),
  Food(name: "Burger", calories: 295, protein: 17, carbs: 30, fat: 12),
  Food(name: "Pizza", calories: 285, protein: 12, carbs: 36, fat: 10),
];
